/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import Classes.*;

import com.sun.tools.javac.Main;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santi
 */
public class ComprarCombo extends javax.swing.JFrame {

    /**
     * Creates new form ComprarCombo
     */
        List<Cliente> listaclientes = new ArrayList<>();
        List<Filme> listafilmes = new ArrayList<>();
    
    CardLayout cardLayout;
    
    public ComprarCombo() {
        initComponents();
       
        cardLayout = (CardLayout) (mainCard.getLayout());
        try {
            updateClientTable();
            updateFilmTable();
        } catch (IOException ex) {
            Logger.getLogger(ComprarCombo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(int i = 0; i < clientTable.getRowCount(); i++){
            boolean estudante = clientTable.getValueAt(i, 3).equals("true");
            listaclientes.add(new Cliente(clientTable.getValueAt(i,1).toString(), Integer.parseInt(clientTable.getValueAt(i, 2).toString()), estudante));
        }
        for(int i = 0; i < filmTable.getRowCount(); i++){
            listafilmes.add(new Filme(filmTable.getValueAt(i,1).toString(), Integer.parseInt(filmTable.getValueAt(i, 2).toString())));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        but1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        but2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        but3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        but4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        but5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        mainCard = new javax.swing.JPanel();
        clientes = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        clientFindField = new javax.swing.JTextField();
        Header2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        clientNameField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        clientAgeSpinner = new javax.swing.JSpinner();
        clientStudentBox = new javax.swing.JCheckBox();
        addClientButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        removeClientButton = new javax.swing.JButton();
        Filmes = new javax.swing.JPanel();
        Header3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        filmNameField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        filmStarsSpinner = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        filmTable = new javax.swing.JTable();
        addFilmButton = new javax.swing.JButton();
        filmFindField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        removeFilmButton = new javax.swing.JButton();
        Sessoes = new javax.swing.JPanel();
        Header4 = new javax.swing.JLabel();
        sessionComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        sessionCapacity = new javax.swing.JSpinner();
        addSessionButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        filmTable1 = new javax.swing.JTable();
        findSessionText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        removeSessionButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        SessionWeekDay = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        SessionHour = new javax.swing.JSpinner();
        SessionMin = new javax.swing.JSpinner();
        Comprar = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        Header5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        clientBuyBox = new javax.swing.JComboBox<>();
        filmBuyBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        sessionBuyBox = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        combos1 = new javax.swing.JPanel();
        Header7 = new javax.swing.JLabel();
        desc7 = new javax.swing.JLabel();
        desc8 = new javax.swing.JLabel();
        desc9 = new javax.swing.JLabel();
        subtitle3 = new javax.swing.JLabel();
        Combo1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        Combo2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        Combo3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        BuyButton = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Combo");
        setName("frame"); // NOI18N
        setPreferredSize(null);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Menu.setBackground(new java.awt.Color(51, 0, 102));
        Menu.setMaximumSize(new java.awt.Dimension(120, 32767));
        Menu.setMinimumSize(new java.awt.Dimension(107, 107));
        Menu.setPreferredSize(new java.awt.Dimension(120, 497));

        but1.setBackground(new java.awt.Color(140, 101, 255));
        but1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but1MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Clientes");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout but1Layout = new javax.swing.GroupLayout(but1);
        but1.setLayout(but1Layout);
        but1Layout.setHorizontalGroup(
            but1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        but1Layout.setVerticalGroup(
            but1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        but2.setBackground(new java.awt.Color(102, 51, 255));
        but2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Filmes");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout but2Layout = new javax.swing.GroupLayout(but2);
        but2.setLayout(but2Layout);
        but2Layout.setHorizontalGroup(
            but2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        but2Layout.setVerticalGroup(
            but2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        but3.setBackground(new java.awt.Color(102, 51, 255));
        but3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sessões");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout but3Layout = new javax.swing.GroupLayout(but3);
        but3.setLayout(but3Layout);
        but3Layout.setHorizontalGroup(
            but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        but3Layout.setVerticalGroup(
            but3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        but4.setBackground(new java.awt.Color(102, 51, 255));
        but4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Comprar");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout but4Layout = new javax.swing.GroupLayout(but4);
        but4.setLayout(but4Layout);
        but4Layout.setHorizontalGroup(
            but4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        but4Layout.setVerticalGroup(
            but4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        but5.setBackground(new java.awt.Color(102, 51, 255));
        but5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sair");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout but5Layout = new javax.swing.GroupLayout(but5);
        but5.setLayout(but5Layout);
        but5Layout.setHorizontalGroup(
            but5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        but5Layout.setVerticalGroup(
            but5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(but3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(but4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(but5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(but1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(but2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        getContentPane().add(Menu);

        mainCard.setBackground(new java.awt.Color(0, 0, 51));
        mainCard.setLayout(new java.awt.CardLayout());

        clientes.setBackground(new java.awt.Color(0, 0, 51));
        clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clientes.setMaximumSize(new java.awt.Dimension(771, 100));

        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Pesquisar:");

        clientFindField.setBackground(new java.awt.Color(204, 204, 204));
        clientFindField.setForeground(new java.awt.Color(51, 51, 51));
        clientFindField.setToolTipText("");
        clientFindField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientFindFieldActionPerformed(evt);
            }
        });
        clientFindField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clientFindFieldKeyReleased(evt);
            }
        });

        Header2.setBackground(new java.awt.Color(255, 255, 255));
        Header2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Header2.setForeground(new java.awt.Color(255, 255, 255));
        Header2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header2.setText("Clientes");
        Header2.setAlignmentX(0.5F);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Nome:");

        clientNameField.setBackground(new java.awt.Color(204, 204, 204));
        clientNameField.setForeground(new java.awt.Color(51, 51, 51));
        clientNameField.setToolTipText("");
        clientNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNameFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Idade:");

        clientAgeSpinner.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        clientAgeSpinner.setOpaque(false);
        clientAgeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientAgeSpinnerStateChanged(evt);
            }
        });

        clientStudentBox.setBackground(new java.awt.Color(0, 0, 51));
        clientStudentBox.setForeground(new java.awt.Color(204, 204, 204));
        clientStudentBox.setText("Estudante");
        clientStudentBox.setOpaque(false);
        clientStudentBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientStudentBoxActionPerformed(evt);
            }
        });

        addClientButton.setBackground(new java.awt.Color(153, 153, 153));
        addClientButton.setText("Adicionar Cliente");
        addClientButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        addClientButton.setBorderPainted(false);
        addClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientButtonActionPerformed(evt);
            }
        });

        clientTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Idade", "Estudante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(clientTable);
        if (clientTable.getColumnModel().getColumnCount() > 0) {
            clientTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            clientTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            clientTable.getColumnModel().getColumn(2).setPreferredWidth(10);
            clientTable.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        removeClientButton.setBackground(new java.awt.Color(153, 153, 153));
        removeClientButton.setText("Remover Cliente");
        removeClientButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        removeClientButton.setBorderPainted(false);
        removeClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeClientButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientesLayout = new javax.swing.GroupLayout(clientes);
        clientes.setLayout(clientesLayout);
        clientesLayout.setHorizontalGroup(
            clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Header2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(clientesLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientesLayout.createSequentialGroup()
                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(clientesLayout.createSequentialGroup()
                                .addComponent(clientFindField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184)
                                .addComponent(removeClientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(clientesLayout.createSequentialGroup()
                                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(clientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientStudentBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(clientAgeSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addClientButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jSeparator1))
                        .addGap(94, 94, 94))))
        );
        clientesLayout.setVerticalGroup(
            clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(Header2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientAgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientStudentBox)
                    .addComponent(addClientButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientFindField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeClientButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        mainCard.add(clientes, "perfil");

        Filmes.setBackground(new java.awt.Color(0, 0, 51));
        Filmes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Filmes.setMaximumSize(new java.awt.Dimension(771, 100));

        Header3.setBackground(new java.awt.Color(255, 255, 255));
        Header3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Header3.setForeground(new java.awt.Color(255, 255, 255));
        Header3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header3.setText("Filmes");
        Header3.setAlignmentX(0.5F);

        filmNameField.setBackground(new java.awt.Color(204, 204, 204));
        filmNameField.setForeground(new java.awt.Color(51, 51, 51));
        filmNameField.setToolTipText("");
        filmNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmNameFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Nome:");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Classificação:");

        filmTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        filmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Classificacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(filmTable);
        if (filmTable.getColumnModel().getColumnCount() > 0) {
            filmTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            filmTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            filmTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        addFilmButton.setBackground(new java.awt.Color(153, 153, 153));
        addFilmButton.setText("Adicionar Filme");
        addFilmButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        addFilmButton.setBorderPainted(false);
        addFilmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFilmButtonActionPerformed(evt);
            }
        });

        filmFindField.setBackground(new java.awt.Color(204, 204, 204));
        filmFindField.setForeground(new java.awt.Color(51, 51, 51));
        filmFindField.setToolTipText("");
        filmFindField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmFindFieldActionPerformed(evt);
            }
        });
        filmFindField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filmFindFieldKeyReleased(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Pesquisar:");

        removeFilmButton.setBackground(new java.awt.Color(153, 153, 153));
        removeFilmButton.setText("Remover Filme");
        removeFilmButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        removeFilmButton.setBorderPainted(false);
        removeFilmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFilmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FilmesLayout = new javax.swing.GroupLayout(Filmes);
        Filmes.setLayout(FilmesLayout);
        FilmesLayout.setHorizontalGroup(
            FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilmesLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Header3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(FilmesLayout.createSequentialGroup()
                            .addGroup(FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(filmFindField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(FilmesLayout.createSequentialGroup()
                                    .addGap(184, 184, 184)
                                    .addComponent(addFilmButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                                .addGroup(FilmesLayout.createSequentialGroup()
                                    .addGap(171, 171, 171)
                                    .addComponent(removeFilmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(103, 103, 103))
            .addGroup(FilmesLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(filmNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filmStarsSpinner))
                .addGap(104, 104, 104))
        );
        FilmesLayout.setVerticalGroup(
            FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilmesLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Header3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filmNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filmStarsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(addFilmButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmFindField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeFilmButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        mainCard.add(Filmes, "filmes");

        Sessoes.setBackground(new java.awt.Color(0, 0, 51));
        Sessoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Sessoes.setMaximumSize(new java.awt.Dimension(771, 100));

        Header4.setBackground(new java.awt.Color(255, 255, 255));
        Header4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Header4.setForeground(new java.awt.Color(255, 255, 255));
        Header4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header4.setText("Sessões");
        Header4.setAlignmentX(0.5F);

        sessionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sessionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionComboBoxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Capacidade:");

        sessionCapacity.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        sessionCapacity.setOpaque(false);
        sessionCapacity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sessionCapacityStateChanged(evt);
            }
        });

        addSessionButton.setBackground(new java.awt.Color(153, 153, 153));
        addSessionButton.setText("Adicionar Sessão");
        addSessionButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        addSessionButton.setBorderPainted(false);
        addSessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSessionButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Filme:");

        filmTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        filmTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Sessão", "Filme", "Horário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(filmTable1);
        if (filmTable1.getColumnModel().getColumnCount() > 0) {
            filmTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            filmTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            filmTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        findSessionText.setBackground(new java.awt.Color(204, 204, 204));
        findSessionText.setForeground(new java.awt.Color(51, 51, 51));
        findSessionText.setToolTipText("");

        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Pesquisar:");

        removeSessionButton.setBackground(new java.awt.Color(153, 153, 153));
        removeSessionButton.setText("Remover Sessão");
        removeSessionButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        removeSessionButton.setBorderPainted(false);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Dia:");

        SessionWeekDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado" }));
        SessionWeekDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SessionWeekDayActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Hora/min");

        SessionHour.setModel(new javax.swing.SpinnerNumberModel(0, null, 23, 1));

        SessionMin.setModel(new javax.swing.SpinnerNumberModel(0, null, 59, 1));
        SessionMin.setToolTipText("");

        javax.swing.GroupLayout SessoesLayout = new javax.swing.GroupLayout(Sessoes);
        Sessoes.setLayout(SessoesLayout);
        SessoesLayout.setHorizontalGroup(
            SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessoesLayout.createSequentialGroup()
                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SessoesLayout.createSequentialGroup()
                        .addContainerGap(108, Short.MAX_VALUE)
                        .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SessoesLayout.createSequentialGroup()
                                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(sessionCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(SessoesLayout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(sessionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(SessoesLayout.createSequentialGroup()
                                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Header4, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SessoesLayout.createSequentialGroup()
                                        .addComponent(SessionWeekDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(SessoesLayout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(248, 248, 248))
                                            .addGroup(SessoesLayout.createSequentialGroup()
                                                .addComponent(SessionHour, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(SessionMin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(214, 214, 214)))))
                                .addGap(0, 5, Short.MAX_VALUE))))
                    .addGroup(SessoesLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(SessoesLayout.createSequentialGroup()
                                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(findSessionText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removeSessionButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addSessionButton, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(105, 105, 105))
        );
        SessoesLayout.setVerticalGroup(
            SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessoesLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(Header4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sessionCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(8, 8, 8)
                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SessionWeekDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSessionButton)
                    .addComponent(SessionHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SessionMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SessoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findSessionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeSessionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        mainCard.add(Sessoes, "sessoes");

        Comprar.setBackground(new java.awt.Color(0, 0, 51));
        Comprar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Comprar.setMaximumSize(new java.awt.Dimension(771, 100));

        Header5.setBackground(new java.awt.Color(255, 255, 255));
        Header5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Header5.setForeground(new java.awt.Color(255, 255, 255));
        Header5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header5.setText("Comprar");
        Header5.setAlignmentX(0.5F);

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Cliente:");

        clientBuyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clientBuyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientBuyBoxActionPerformed(evt);
            }
        });

        filmBuyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filmBuyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmBuyBoxActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Filme:");

        sessionBuyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sessionBuyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionBuyBoxActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Sessão:");

        combos1.setBackground(new java.awt.Color(0, 0, 51));
        combos1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        combos1.setMaximumSize(new java.awt.Dimension(771, 100));

        Header7.setBackground(new java.awt.Color(255, 255, 255));
        Header7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Header7.setForeground(new java.awt.Color(255, 255, 255));
        Header7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header7.setText("Escolha Seu Combo");
        Header7.setAlignmentX(0.5F);

        desc7.setBackground(new java.awt.Color(102, 102, 102));
        desc7.setForeground(new java.awt.Color(204, 204, 204));
        desc7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc7.setText("20% de Desconto");

        desc8.setBackground(new java.awt.Color(102, 102, 102));
        desc8.setForeground(new java.awt.Color(204, 204, 204));
        desc8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc8.setText("10% de Desconto");

        desc9.setBackground(new java.awt.Color(102, 102, 102));
        desc9.setForeground(new java.awt.Color(204, 204, 204));
        desc9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc9.setText("15% de Desconto");

        subtitle3.setBackground(new java.awt.Color(153, 153, 153));
        subtitle3.setForeground(new java.awt.Color(204, 204, 204));
        subtitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitle3.setText("Escolha um combo e ganhe desconto no seu pedido");

        Combo1.setBackground(new java.awt.Color(51, 0, 102));

        jLabel28.setBackground(new java.awt.Color(51, 0, 102));
        jLabel28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Refri + Chocolate");
        jLabel28.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout Combo1Layout = new javax.swing.GroupLayout(Combo1);
        Combo1.setLayout(Combo1Layout);
        Combo1Layout.setHorizontalGroup(
            Combo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Combo1Layout.setVerticalGroup(
            Combo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Combo2.setBackground(new java.awt.Color(51, 0, 102));

        jLabel29.setBackground(new java.awt.Color(51, 0, 102));
        jLabel29.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Refri + pipoca");
        jLabel29.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout Combo2Layout = new javax.swing.GroupLayout(Combo2);
        Combo2.setLayout(Combo2Layout);
        Combo2Layout.setHorizontalGroup(
            Combo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Combo2Layout.setVerticalGroup(
            Combo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Combo3.setBackground(new java.awt.Color(51, 0, 102));

        jLabel30.setBackground(new java.awt.Color(51, 0, 102));
        jLabel30.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Refri + Pipoca");
        jLabel30.setToolTipText("");
        jLabel30.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel31.setBackground(new java.awt.Color(51, 0, 102));
        jLabel31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("+ Chocolate");
        jLabel31.setToolTipText("");
        jLabel31.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout Combo3Layout = new javax.swing.GroupLayout(Combo3);
        Combo3.setLayout(Combo3Layout);
        Combo3Layout.setHorizontalGroup(
            Combo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Combo3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Combo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Combo3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel31))
                    .addComponent(jLabel30))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Combo3Layout.setVerticalGroup(
            Combo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Combo3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap())
        );

        javax.swing.GroupLayout combos1Layout = new javax.swing.GroupLayout(combos1);
        combos1.setLayout(combos1Layout);
        combos1Layout.setHorizontalGroup(
            combos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(combos1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(combos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(combos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(subtitle3)
                        .addComponent(Header7, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(combos1Layout.createSequentialGroup()
                        .addGroup(combos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desc8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(combos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desc9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(combos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(desc7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Combo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        combos1Layout.setVerticalGroup(
            combos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(combos1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Header7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(combos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Combo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(combos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desc8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        BuyButton.setBackground(new java.awt.Color(51, 0, 102));

        jLabel32.setBackground(new java.awt.Color(51, 0, 102));
        jLabel32.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Comprar");
        jLabel32.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout BuyButtonLayout = new javax.swing.GroupLayout(BuyButton);
        BuyButton.setLayout(BuyButtonLayout);
        BuyButtonLayout.setHorizontalGroup(
            BuyButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );
        BuyButtonLayout.setVerticalGroup(
            BuyButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout ComprarLayout = new javax.swing.GroupLayout(Comprar);
        Comprar.setLayout(ComprarLayout);
        ComprarLayout.setHorizontalGroup(
            ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComprarLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combos1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Header5, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ComprarLayout.createSequentialGroup()
                            .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(clientBuyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21))
                            .addGap(121, 121, 121)
                            .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(filmBuyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sessionBuyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)))))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComprarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BuyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        ComprarLayout.setVerticalGroup(
            ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComprarLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Header5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ComprarLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clientBuyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ComprarLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(filmBuyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ComprarLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sessionBuyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(combos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BuyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        mainCard.add(Comprar, "combos");

        getContentPane().add(mainCard);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
   
    Color selected = new Color(140,101,255);
    Color reset = new Color(102,51,255);
    
    
    private void but2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but2MouseClicked
        cardLayout.show(mainCard, "filmes");
        but2.setBackground(selected);
        but1.setBackground(reset);
        but3.setBackground(reset);
        but4.setBackground(reset);
    }//GEN-LAST:event_but2MouseClicked

    private void but5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_but5MouseClicked

    private void but1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but1MouseClicked
        cardLayout.show(mainCard, "perfil");
        but2.setBackground(reset);
        but1.setBackground(selected);
        but3.setBackground(reset);
        but4.setBackground(reset);
    }//GEN-LAST:event_but1MouseClicked

    private void but3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but3MouseClicked
        cardLayout.show(mainCard, "sessoes");
        but2.setBackground(reset);
        but1.setBackground(reset);
        but3.setBackground(selected);
        but4.setBackground(reset);
    }//GEN-LAST:event_but3MouseClicked

    private void but4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but4MouseClicked
        cardLayout.show(mainCard, "combos");
        but2.setBackground(reset);
        but1.setBackground(reset);
        but3.setBackground(reset);
        but4.setBackground(selected);
    }//GEN-LAST:event_but4MouseClicked

    private void clientNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNameFieldActionPerformed

    private void clientStudentBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientStudentBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientStudentBoxActionPerformed

    private void addClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientButtonActionPerformed
        if(clientNameField.getText().equals("") || clientAgeSpinner.getValue().equals(0)){ // -----------------> ADD CLIENT BUTTON
            JOptionPane.showMessageDialog(this, "Por favor, insira todas as informações!");
        }
        else{
            insertClientRow(clientNameField.getText(), (int)clientAgeSpinner.getValue(), clientStudentBox.isSelected());
            listaclientes.add(new Cliente(clientNameField.getText(), (int)clientAgeSpinner.getValue(), clientStudentBox.isSelected()));
            insertClientText();
        }
    }//GEN-LAST:event_addClientButtonActionPerformed

    private void insertClientRow(String name, int age, boolean isStudent){
        DefaultTableModel model = (DefaultTableModel)clientTable.getModel(); // -----------------> INSERT CLIENT ROW TABELA
        Object[] data = {clientTable.getRowCount(),name, age, isStudent};
        model.addRow(data);
        JOptionPane.showMessageDialog(null, "O Cliente foi Adicionado Com Sucesso");
    }
    
    private void insertClientText(){
        try {
            FileWriter writer = new FileWriter("Clientes.txt",false); // --------------------> CONVERT CLIENT TABLE TO TXT
            BufferedWriter bw = new BufferedWriter(writer);
                
                
            for(int i = 0; i < clientTable.getRowCount(); i++){
                for(int j = 0; j < clientTable.getColumnCount(); j++){//column
                 bw.write(clientTable.getValueAt(i,j).toString()+"/");
                }
                bw.newLine();
            }
            bw.close();
            writer.close();
            updateClientTable();
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro!");
        }
    
    }
    
    private void updateClientTable() throws IOException{
        String filePath = "Clientes.txt";
        File file = new File(filePath);
        
        try {
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            
            DefaultTableModel model = (DefaultTableModel)clientTable.getModel();
            
            Object[] tableLines = br.lines().toArray();
            
            model.setRowCount(0);
            for(int i = 0; i < tableLines.length; i++){
                String line = tableLines[i].toString().trim();
                Object[] dataRow = line.split("/");
                boolean estudante = dataRow[3].equals("true"); 
                Object[] filtered = {dataRow[0], dataRow[1], dataRow[2], estudante};
                model.addRow(filtered);                
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ComprarCombo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    private void clientFindFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientFindFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientFindFieldActionPerformed

    private void clientFindFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientFindFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_clientFindFieldKeyReleased

    private void clientAgeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientAgeSpinnerStateChanged

    }//GEN-LAST:event_clientAgeSpinnerStateChanged

    private void filmNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filmNameFieldActionPerformed

    private void addFilmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFilmButtonActionPerformed
          if(filmNameField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Por favor, insira todas as informações!");
        }
        else{
            insertFilmRow(filmNameField.getText(), (int)filmStarsSpinner.getValue());
            insertFilmText();
        }
    }//GEN-LAST:event_addFilmButtonActionPerformed

        private void insertFilmRow(String name, int star){
            DefaultTableModel model = (DefaultTableModel)filmTable.getModel();
            Object[] data = {filmTable.getRowCount(),name, star};
            model.addRow(data);
            JOptionPane.showMessageDialog(null, "O Filme foi Adicionado Com Sucesso");
        }
    
    
        private void insertFilmText(){
        try {
            FileWriter writer = new FileWriter("Filmes.txt",false);
            BufferedWriter bw = new BufferedWriter(writer);
                
                
            for(int i = 0; i < filmTable.getRowCount(); i++){
                for(int j = 0; j < filmTable.getColumnCount(); j++){//column
                 bw.write(filmTable.getValueAt(i,j).toString()+"/");
                }
                bw.newLine();
            }
            bw.close();
            writer.close();
            updateFilmTable();
            
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro!");
        }
    
    }
    
        
        private void updateFilmTable() throws IOException{
          String filePath = "Filmes.txt";
        File file = new File(filePath);
        
        try {
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            
            DefaultTableModel model = (DefaultTableModel)filmTable.getModel();
            
            Object[] tableLines = br.lines().toArray();
            
            
            model.setRowCount(0);
            for(int i = 0; i < tableLines.length; i++){
                String line = tableLines[i].toString().trim();
                Object[] dataRow = line.split("/");
                model.addRow(dataRow);
                
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ComprarCombo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
        
    
    
    private void filmFindFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmFindFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filmFindFieldActionPerformed

    private void filmFindFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filmFindFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_filmFindFieldKeyReleased

    private void removeClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeClientButtonActionPerformed
        if(filmTable.getSelectedRowCount() == 1){    
        listaclientes.remove(clientTable.getSelectedRow());    
            DefaultTableModel model = (DefaultTableModel)clientTable.getModel();
            if(clientTable.getSelectedRowCount() == 1){
            for(int i = clientTable.getSelectedRow(); i < clientTable.getRowCount(); i ++){
                model.setValueAt(i-1, i, 0);
            }
            model.removeRow(clientTable.getSelectedRow());
            insertClientText();
            JOptionPane.showMessageDialog(null, "O Cliente foi Removido Com Sucesso");
            }
        }
            else{
                JOptionPane.showMessageDialog(null, "Selecione apenas UMA linha");
            }
            
    }//GEN-LAST:event_removeClientButtonActionPerformed

    private void removeFilmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFilmButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel)filmTable.getModel();
            if(filmTable.getSelectedRowCount() == 1){
            for(int i = filmTable.getSelectedRow(); i < filmTable.getRowCount(); i ++){
                model.setValueAt(i-1, i, 0);
            }
            model.removeRow(filmTable.getSelectedRow());
            insertFilmText();
            JOptionPane.showMessageDialog(null, "O Filme foi Removido Com Sucesso");
            }
            else{
                JOptionPane.showMessageDialog(null, "Selecione apenas um filme");
            }
    }//GEN-LAST:event_removeFilmButtonActionPerformed

    private void sessionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sessionComboBoxActionPerformed

    private void sessionCapacityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sessionCapacityStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sessionCapacityStateChanged

    private void addSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSessionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSessionButtonActionPerformed

    private void SessionWeekDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SessionWeekDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SessionWeekDayActionPerformed

    private void clientBuyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientBuyBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientBuyBoxActionPerformed

    private void filmBuyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmBuyBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filmBuyBoxActionPerformed

    private void sessionBuyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionBuyBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sessionBuyBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprarCombo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuyButton;
    private javax.swing.JPanel Combo1;
    private javax.swing.JPanel Combo2;
    private javax.swing.JPanel Combo3;
    private javax.swing.JPanel Comprar;
    private javax.swing.JPanel Filmes;
    private javax.swing.JLabel Header2;
    private javax.swing.JLabel Header3;
    private javax.swing.JLabel Header4;
    private javax.swing.JLabel Header5;
    private javax.swing.JLabel Header7;
    private javax.swing.JPanel Menu;
    private javax.swing.JSpinner SessionHour;
    private javax.swing.JSpinner SessionMin;
    private javax.swing.JComboBox<String> SessionWeekDay;
    private javax.swing.JPanel Sessoes;
    private javax.swing.JButton addClientButton;
    private javax.swing.JButton addFilmButton;
    private javax.swing.JButton addSessionButton;
    private javax.swing.JPanel but1;
    private javax.swing.JPanel but2;
    private javax.swing.JPanel but3;
    private javax.swing.JPanel but4;
    private javax.swing.JPanel but5;
    private javax.swing.JSpinner clientAgeSpinner;
    private javax.swing.JComboBox<String> clientBuyBox;
    private javax.swing.JTextField clientFindField;
    private javax.swing.JTextField clientNameField;
    private javax.swing.JCheckBox clientStudentBox;
    private javax.swing.JTable clientTable;
    private javax.swing.JPanel clientes;
    private javax.swing.JPanel combos1;
    private javax.swing.JLabel desc7;
    private javax.swing.JLabel desc8;
    private javax.swing.JLabel desc9;
    private javax.swing.JComboBox<String> filmBuyBox;
    private javax.swing.JTextField filmFindField;
    private javax.swing.JTextField filmNameField;
    private javax.swing.JSpinner filmStarsSpinner;
    private javax.swing.JTable filmTable;
    private javax.swing.JTable filmTable1;
    private javax.swing.JTextField findSessionText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel mainCard;
    private javax.swing.JButton removeClientButton;
    private javax.swing.JButton removeFilmButton;
    private javax.swing.JButton removeSessionButton;
    private javax.swing.JComboBox<String> sessionBuyBox;
    private javax.swing.JSpinner sessionCapacity;
    private javax.swing.JComboBox<String> sessionComboBox;
    private javax.swing.JLabel subtitle3;
    // End of variables declaration//GEN-END:variables
}
